name: Fetch Github repos about various topics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  GITHUB_PAT: ${{ secrets.QUERY_GH }}
  NEO4J_URI: ${{ vars.NEO4J_URI }}
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      - run: npm ci
      - run: npx nx run kg-fetch:build
  update-neo4j:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: node dist/apps/kg-fetch/main.js fetchRepos --from $(date -I -d '-2 day') --to $(date -I) --interval 1 neo4j
