name: Fetch Github repos about various topics

on:
  schedule:
    - cron: '0 0 * * *'
env:
  GITHUB_PAT: ${{ secrets.QUERY_GH }}
  NEO4J_URI: neo4j+s://7ef98a07.databases.neo4j.io
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  test_schedule:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running at" $(date -I) "and yesterday was" $(date -I -v-1d)
      - run: node --version
      - run: env
      - run: node dist/apps/kg-fetch/main.js fetchRepos --from "$(date -I -v-2d)" --to "$(date -I)" --interval 1 neo4j
